### PR TITLE
doc: add description of build steps for the vsix

### PR DESCRIPTION
**Pull request by filak-sap**

### CODE REVIEW

**Comment by filak-sap** [comment]
@larshp Alright, so what you had to do? How did you get the vsix file? The file is not a part of the repository.

**Comment by larshp** [comment]
https://github.com/marcellourbani/vscode_abap_remote_fs/releases

it was there for 0.0.1 and 0.0.2, guess @marcellourbani forgot to add it for 0.0.3

**Comment by larshp** [comment]
perhaps split the Setup section into:
* Compiling and installing from source
and
* Installing release

**Comment by filak-sap** [comment]
Sure thing! Done already.

**Comment by marcellourbani** [comment]
Ooops! was positive I did!

Fixed now

**Pull request merged**
