### PR TITLE
Add select Query

### PR DESCRIPTION
**Pull request by dh4rry**
New Command "AbapFs Select Query" and view to execute select Querys on tables and (cds-views).
fix [#137]

### CODE REVIEW

**Comment by marcellourbani** [comment]
Hello, and thanks for the contribution!
Will look into it better as soon as I have a minute, but on a cursory look I'm not sure I understand:

- how do you register the new command
- where's the select

PS: I did add the selection code to the ADT API a month or two ago, didn't find the time to integrate it yet. This is a great addition!

**Comment by marcellourbani** [comment]
btw, I see you're still working on it, will give you some time to settle :)

**Comment by dh4rry** [comment]
I've missed to commit commands.ts. Now it is there.

In the new query view the user can enter a select statement and execute it. The query is executed by client.runQuery

**Comment by marcellourbani** [comment]
Just managed to test it. works fine both on cloud and on my 7.50 server
Thanks a lot, this is a great addition. CI will publish it in no time :)

**Pull request merged**
